before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gconf2
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 10

script:
  - "npm test"

language: node_js

node_js:
  - 0.8